In [ ]:
numbers = [1,2,3,4,5,6,7,8]

In [ ]:
double_numbers = []

In [ ]:
# Non-Pythonic code

for i in range(len(numbers)):
    double_numbers.append(numbers[i] * 2)
    
    
    

In [ ]:
double_numbers

In [ ]:
# Pythonic code


double_no = [ x * 2 for x in numbers ]

In [ ]:
  for i in double_no:
        if i % 2 == 0:
            print(i)


# __Numpy arrays__ are __homogenuous__ ( elements should have the same dataType )

In [7]:
import numpy as np

In [8]:
num_np_ints = np.array([20,1,25,33,102])

In [9]:
num_np_ints

array([ 20,   1,  25,  33, 102])

In [10]:
print(type(num_np_ints))

<class 'numpy.ndarray'>


## __dtype__ it is used to check __individual__ type

In [11]:
num_np_ints.dtype

dtype('int64')

In [12]:
new_data = num_np_ints / 10

In [13]:
type(new_data)

numpy.ndarray

In [14]:
new_data.dtype

dtype('float64')

In [15]:
new_data

array([ 2. ,  0.1,  2.5,  3.3, 10.2])

# Diference between __simple_2D_array__  and __Numpy_2D_array__

In [16]:
# simple_2D_array 

simple_2d_array = [
    [12,44,33],
    [30,1,4]
]

In [17]:
simple_2d_array[1][1]

1

In [18]:
[ row[0] for row in simple_2d_array ]

[12, 30]

## Indexing capabilities of numpy array __easiest__ one 

In [19]:
# Numpy_2D_array

numpy_array = np.array([
    [10,11,13],
    [16,1,3]
])

In [20]:
numpy_array[1,1]

1

In [21]:
numpy_array[0:,1]

array([11,  1])

In [22]:
 boolean_array = np.array([10,-26,2,-3])

In [23]:
 boolean_array > 0

array([ True, False,  True, False])

In [24]:
positive_numbers=  boolean_array[ boolean_array > 0 ] 

In [25]:
positive_numbers +1.5

array([11.5,  3.5])

## Using list comprehension for a __list__ it can be done in this way.

In [26]:
list_array = [1,-2,33,6,-45,8]

In [27]:
result = [ num for num in list_array if num > 0]

In [28]:
result

[1, 33, 6, 8]

## Code to be timed / Using __%timeit__

In [29]:
rand_nums = np.random.rand(1000)

In [30]:
rand_nums

array([0.18207642, 0.14081249, 0.50237166, 0.43115212, 0.24307498,
       0.17631977, 0.86752708, 0.01834451, 0.07995001, 0.29828423,
       0.06482887, 0.92356444, 0.66115896, 0.73214802, 0.82622937,
       0.87249035, 0.62989397, 0.9508645 , 0.02546733, 0.1621857 ,
       0.90515903, 0.53065236, 0.19585017, 0.87889514, 0.36118341,
       0.86353163, 0.83415425, 0.54401774, 0.1920745 , 0.990875  ,
       0.39537847, 0.86003239, 0.71191874, 0.38149841, 0.16328508,
       0.57934694, 0.43982608, 0.96978224, 0.40228829, 0.79493792,
       0.14572156, 0.272316  , 0.01122562, 0.79502044, 0.06919636,
       0.83115503, 0.90435798, 0.9704182 , 0.44821985, 0.73152153,
       0.76162184, 0.27525607, 0.21202072, 0.76941829, 0.21845785,
       0.12704171, 0.79828131, 0.9064614 , 0.60025881, 0.95823422,
       0.51474487, 0.87052513, 0.95953143, 0.12415501, 0.64069252,
       0.34290867, 0.84097872, 0.52888526, 0.77491848, 0.93389536,
       0.73134543, 0.31804241, 0.02568693, 0.33686138, 0.00318

In [31]:
%timeit rand_nums = np.random.rand(1000)

6.94 µs ± 59.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [32]:
## -r = numbers of runs, r2 = two runs
## -n = number of loops, n10 = 10 loops
%timeit -r2 -n10 rand_nums = np.random.rand(1000)

The slowest run took 6.78 times longer than the fastest. This could mean that an intermediate result is being cached.
44 µs ± 32.7 µs per loop (mean ± std. dev. of 2 runs, 10 loops each)


In [33]:
%timeit formal_dict = dict()

87.6 ns ± 3.61 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [34]:
%timeit literal_dict = {}

25.4 ns ± 0.481 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


# Checking memory usage

In [35]:
import sys

In [36]:
data = [23,67]

In [37]:
sys.getsizeof(data)

72

In [38]:
data1 = np.array([23,67])

In [39]:
sys.getsizeof(data1)

112

## Code profiling: __line_profiler__ with __%lprun__

In [40]:
def even_num(num):
    if num % 2 == 0:
        print(num)
    else:
        print('not even')

In [41]:
even_num(9)

not even


In [42]:
## load first the line_profiler

%load_ext line_profiler

In [43]:
%lprun  -f even_num even_num(9)

not even


Timer unit: 1e-06 s

Total time: 0.000841 s
File: <ipython-input-40-ef630fa43f15>
Function: even_num at line 1

Line #      Hits         Time  Per Hit   % Time  Line Contents
     1                                           def even_num(num):
     2         1          4.0      4.0      0.5      if num % 2 == 0:
     3                                                   print(num)
     4                                               else:
     5         1        837.0    837.0     99.5          print('not even')

## Code profiling: __memory_profiler__
### check line by line memory usages

In [44]:
from funtions import even_num

In [45]:
%load_ext memory_profiler 

In [46]:
%mprun -f even_num even_num(28)

28



Filename: /Users/olivierla412/projects/data_camp/funtions.py

Line #    Mem usage    Increment  Occurences   Line Contents
     1     62.5 MiB     62.5 MiB           1   def even_num(num):
     2     62.5 MiB      0.0 MiB           1       if num % 2 == 0:
     3     62.5 MiB      0.0 MiB           1           print(num)
     4                                             else:
     5                                                 print('not even')

## Combining objects

In [55]:
tast = ['coffee','orange','mango']
points = [45,100,20]

In [69]:
combined = []

In [49]:
x = enumerate(tast)

In [50]:
list(x)

[(0, 'coffee'), (1, 'orange'), (2, 'mango')]

In [70]:
for i ,value in enumerate(tast):
    combined.append((value, points[i]))

In [71]:
print(combined)

[('coffee', 45), ('orange', 100), ('mango', 20)]


## Combining objects using __zip()__ function

In [82]:
data1 = ['Orange','Mango','Bananas','Apple']
data2 = [100,101,102,103]

In [84]:
resulta = zip(data1, data2)

In [77]:
resulta

In [85]:
## result = list(resulta)
result = [ *resulta ]

In [86]:
result

[('Orange', 100), ('Mango', 101), ('Bananas', 102), ('Apple', 103)]

# __collections__.__Counter__

### help to build a __dict__ from a list using __counter__

In [97]:
data1 = ['Orange','Mango','Bananas','Apple']


In [98]:
from collections import Counter

In [99]:
dict_data = Counter(data1)

In [100]:
print(dict_data )

Counter({'Orange': 1, 'Mango': 1, 'Bananas': 1, 'Apple': 1})


## Combinations with loops

In [101]:
data1 = ['Orange','Mango','Bananas','Apple']


In [102]:
combined = []

In [103]:
for x in data1:
    for y in data1:
        if x == y :
            continue
        if ((x,y) not in combined) & ((y,x) not in combined):
            combined.append((x,y))

In [104]:
print(combined)

[('Orange', 'Mango'), ('Orange', 'Bananas'), ('Orange', 'Apple'), ('Mango', 'Bananas'), ('Mango', 'Apple'), ('Bananas', 'Apple')]


# __itertools__.__combinations()__ give better option than above example

In [106]:
from itertools import combinations

In [123]:
data1 = ['Orange','Mango','Bananas','Apple']


#### create a combination of called __object1__

In [124]:
object1 = combinations(data1, 2)

In [125]:
result = [*object1]

In [126]:
result

[('Orange', 'Mango'),
 ('Orange', 'Bananas'),
 ('Orange', 'Apple'),
 ('Mango', 'Bananas'),
 ('Mango', 'Apple'),
 ('Bananas', 'Apple')]

In [128]:
data1 = {'Orange','Mango','Bananas','Apple'}
data2 = {'Orange','Mango','Greep','Apple'}


In [129]:
data1.intersection(data2)

{'Apple', 'Mango', 'Orange'}

In [130]:
data1.difference(data2)

{'Bananas'}

## to item in one set but not in the other 

In [132]:
da = data1.symmetric_difference(data2)

In [133]:
da

{'Bananas', 'Greep'}

In [134]:
daa = data2.union(data1)

In [135]:
daa

{'Apple', 'Bananas', 'Greep', 'Mango', 'Orange'}

## Uniqueness using a __for loop__

In [138]:
data = ['Orange','Mango','Bananas','Apple','Apple','Mango','Lemon']


In [139]:
uniq = []

In [140]:
for item in data:
    if item not in uniq:
        uniq.append(item)

In [141]:
print(uniq)

['Orange', 'Mango', 'Bananas', 'Apple', 'Lemon']


## set is a collection of __distinct__ elements

In [145]:
set_data = set(data)

In [146]:
set_data

{'Apple', 'Bananas', 'Lemon', 'Mango', 'Orange'}