In [ ]:
numbers = [1,2,3,4,5,6,7,8]

In [ ]:
double_numbers = []

In [ ]:
# Non-Pythonic code

for i in range(len(numbers)):
    double_numbers.append(numbers[i] * 2)
    
    
    

In [ ]:
double_numbers

In [ ]:
# Pythonic code


double_no = [ x * 2 for x in numbers ]

In [ ]:
  for i in double_no:
        if i % 2 == 0:
            print(i)


# __Numpy arrays__ are __homogenuous__ ( elements should have the same dataType )

In [7]:
import numpy as np

In [8]:
num_np_ints = np.array([20,1,25,33,102])

In [9]:
num_np_ints

array([ 20,   1,  25,  33, 102])

In [10]:
print(type(num_np_ints))

<class 'numpy.ndarray'>


## __dtype__ it is used to check __individual__ type

In [11]:
num_np_ints.dtype

dtype('int64')

In [12]:
new_data = num_np_ints / 10

In [13]:
type(new_data)

numpy.ndarray

In [14]:
new_data.dtype

dtype('float64')

In [15]:
new_data

array([ 2. ,  0.1,  2.5,  3.3, 10.2])

# Diference between __simple_2D_array__  and __Numpy_2D_array__

In [16]:
# simple_2D_array 

simple_2d_array = [
    [12,44,33],
    [30,1,4]
]

In [17]:
simple_2d_array[1][1]

1

In [18]:
[ row[0] for row in simple_2d_array ]

[12, 30]

## Indexing capabilities of numpy array __easiest__ one 

In [19]:
# Numpy_2D_array

numpy_array = np.array([
    [10,11,13],
    [16,1,3]
])

In [20]:
numpy_array[1,1]

1

In [21]:
numpy_array[0:,1]

array([11,  1])

In [22]:
 boolean_array = np.array([10,-26,2,-3])

In [23]:
 boolean_array > 0

array([ True, False,  True, False])

In [24]:
positive_numbers=  boolean_array[ boolean_array > 0 ] 

In [25]:
positive_numbers +1.5

array([11.5,  3.5])

## Using list comprehension for a __list__ it can be done in this way.

In [26]:
list_array = [1,-2,33,6,-45,8]

In [27]:
result = [ num for num in list_array if num > 0]

In [28]:
result

[1, 33, 6, 8]

## Code to be timed / Using __%timeit__

In [149]:
##rand_nums = np.random.rand(1000)##

In [150]:
##rand_nums##

In [31]:
%timeit rand_nums = np.random.rand(1000)

6.94 µs ± 59.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [32]:
## -r = numbers of runs, r2 = two runs
## -n = number of loops, n10 = 10 loops
%timeit -r2 -n10 rand_nums = np.random.rand(1000)

The slowest run took 6.78 times longer than the fastest. This could mean that an intermediate result is being cached.
44 µs ± 32.7 µs per loop (mean ± std. dev. of 2 runs, 10 loops each)


In [33]:
%timeit formal_dict = dict()

87.6 ns ± 3.61 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [34]:
%timeit literal_dict = {}

25.4 ns ± 0.481 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


# Checking memory usage

In [35]:
import sys

In [36]:
data = [23,67]

In [37]:
sys.getsizeof(data)

72

In [38]:
data1 = np.array([23,67])

In [39]:
sys.getsizeof(data1)

112

## Code profiling: __line_profiler__ with __%lprun__

In [40]:
def even_num(num):
    if num % 2 == 0:
        print(num)
    else:
        print('not even')

In [41]:
even_num(9)

not even


In [42]:
## load first the line_profiler

%load_ext line_profiler

In [43]:
%lprun  -f even_num even_num(9)

not even


Timer unit: 1e-06 s

Total time: 0.000841 s
File: <ipython-input-40-ef630fa43f15>
Function: even_num at line 1

Line #      Hits         Time  Per Hit   % Time  Line Contents
     1                                           def even_num(num):
     2         1          4.0      4.0      0.5      if num % 2 == 0:
     3                                                   print(num)
     4                                               else:
     5         1        837.0    837.0     99.5          print('not even')

## Code profiling: __memory_profiler__
### check line by line memory usages

In [44]:
from funtions import even_num

In [45]:
%load_ext memory_profiler 

In [46]:
%mprun -f even_num even_num(28)

28



Filename: /Users/olivierla412/projects/data_camp/funtions.py

Line #    Mem usage    Increment  Occurences   Line Contents
     1     62.5 MiB     62.5 MiB           1   def even_num(num):
     2     62.5 MiB      0.0 MiB           1       if num % 2 == 0:
     3     62.5 MiB      0.0 MiB           1           print(num)
     4                                             else:
     5                                                 print('not even')

## Combining objects

In [55]:
tast = ['coffee','orange','mango']
points = [45,100,20]

In [69]:
combined = []

In [49]:
x = enumerate(tast)

In [50]:
list(x)

[(0, 'coffee'), (1, 'orange'), (2, 'mango')]

In [70]:
for i ,value in enumerate(tast):
    combined.append((value, points[i]))

In [71]:
print(combined)

[('coffee', 45), ('orange', 100), ('mango', 20)]


## Combining objects using __zip()__ function

In [82]:
data1 = ['Orange','Mango','Bananas','Apple']
data2 = [100,101,102,103]

In [84]:
resulta = zip(data1, data2)

In [77]:
resulta

In [85]:
## result = list(resulta)
result = [ *resulta ]

In [86]:
result

[('Orange', 100), ('Mango', 101), ('Bananas', 102), ('Apple', 103)]

# __collections__.__Counter__

### help to build a __dict__ from a list using __counter__

In [97]:
data1 = ['Orange','Mango','Bananas','Apple']


In [98]:
from collections import Counter

In [99]:
dict_data = Counter(data1)

In [100]:
print(dict_data )

Counter({'Orange': 1, 'Mango': 1, 'Bananas': 1, 'Apple': 1})


## Combinations with loops

In [101]:
data1 = ['Orange','Mango','Bananas','Apple']


In [102]:
combined = []

In [103]:
for x in data1:
    for y in data1:
        if x == y :
            continue
        if ((x,y) not in combined) & ((y,x) not in combined):
            combined.append((x,y))

In [104]:
print(combined)

[('Orange', 'Mango'), ('Orange', 'Bananas'), ('Orange', 'Apple'), ('Mango', 'Bananas'), ('Mango', 'Apple'), ('Bananas', 'Apple')]


# __itertools__.__combinations()__ give better option than above example

In [106]:
from itertools import combinations

In [123]:
data1 = ['Orange','Mango','Bananas','Apple']


#### create a combination of called __object1__

In [124]:
object1 = combinations(data1, 2)

In [125]:
result = [*object1]

In [126]:
result

[('Orange', 'Mango'),
 ('Orange', 'Bananas'),
 ('Orange', 'Apple'),
 ('Mango', 'Bananas'),
 ('Mango', 'Apple'),
 ('Bananas', 'Apple')]

In [128]:
data1 = {'Orange','Mango','Bananas','Apple'}
data2 = {'Orange','Mango','Greep','Apple'}


In [129]:
data1.intersection(data2)

{'Apple', 'Mango', 'Orange'}

In [130]:
data1.difference(data2)

{'Bananas'}

## to item in one set but not in the other 

In [132]:
da = data1.symmetric_difference(data2)

In [133]:
da

{'Bananas', 'Greep'}

In [134]:
daa = data2.union(data1)

In [135]:
daa

{'Apple', 'Bananas', 'Greep', 'Mango', 'Orange'}

## Uniqueness using a __for loop__

In [138]:
data = ['Orange','Mango','Bananas','Apple','Apple','Mango','Lemon']


In [139]:
uniq = []

In [140]:
for item in data:
    if item not in uniq:
        uniq.append(item)

In [141]:
print(uniq)

['Orange', 'Mango', 'Bananas', 'Apple', 'Lemon']


## set is a collection of __distinct__ elements

In [145]:
set_data = set(data)

In [146]:
set_data

{'Apple', 'Bananas', 'Lemon', 'Mango', 'Orange'}

In [151]:
yes = 10

# __Eliminating loops__
#### Writing efficient python code 

In [164]:
poke_stats =[
    [100,102,90],
    [10,102,20],
    [44,12,90]
]

In [153]:
new_data =[]

    

In [154]:
for row in poke_stats:
    new_data.append(sum(row))
        

In [155]:
new_data

[292, 132, 146]

### without for loop , using __list comprehension__

In [158]:
data_comp = [ sum(row) for row in poke_stats ]

In [159]:
data_comp

[292, 132, 146]

In [161]:
import numpy as np

In [163]:
poke_stats1 =np.array([
    [100,102,90],
    [10,102,20],
    [44,12,90]
])

In [166]:
type(poke_stats1)

numpy.ndarray

In [169]:
avgs_np = poke_stats1.mean(axis =1)

# axis =1 / mean each { row  }

In [170]:
avgs_np

array([97.33333333, 44.        , 48.66666667])

In [172]:
%timeit -r2 -n4 avgs_np = poke_stats1.mean(axis =1)


16.8 µs ± 5.09 µs per loop (mean ± std. dev. of 2 runs, 4 loops each)


# Good example for better loop

In [178]:
names = ['Absol','Aron','Jynx','Natu','Onix','la412']

In [179]:
attacks = np.array([130,70,50,50,45,120])

In [180]:
total_attack_avg = attacks.mean()

In [182]:
for pokemon, attack in zip(names, attacks):
    if attack > total_attack_avg:
        print(
            
        " {}'s attack: {} greater than total_attack_avg: {}! ".format(pokemon, attack, total_attack_avg))

 Absol's attack: 130 greater than total_attack_avg: 77.5! 
 la412's attack: 120 greater than total_attack_avg: 77.5! 


# Example 2 __combined 3 lists__

In [183]:
names = ['Absol','Aron','Jynx','Natu','Onix','la412']

In [185]:
data_list = [130,70,50,50,45,120]

In [186]:
numbers = [1,2,3,4,5,6]

In [187]:
data = []

In [188]:
for tuple_data in zip(names,data_list,numbers):
    datax = list(tuple_data)
    data.append(datax)
print(data)    

[['Absol', 130, 1], ['Aron', 70, 2], ['Jynx', 50, 3], ['Natu', 50, 4], ['Onix', 45, 5], ['la412', 120, 6]]


## 2nd way to solve the above question

In [189]:
poke_data =[]

In [190]:
for pokemon in zip(names, data_list, numbers):
    poke_data.append(pokemon)

In [202]:
result_data = [*map(list, poke_data)]

## how to used map() and convert a tuple to a list !!!!!

In [201]:
result_data

[['Absol', 130, 1],
 ['Aron', 70, 2],
 ['Jynx', 50, 3],
 ['Natu', 50, 4],
 ['Onix', 45, 5],
 ['la412', 120, 6]]

# Intro to __pandas__ DataFrame __iteration__

In [203]:
data = {
     'Team':["ARI",'ALT','BAL','BOS','CHC'],
     'League':['NL','NL','AL','AL','NL'],
     'Year':[2012,2012,2012,2012,2012],
     'RS':[734,700,712,734,613],
     'RA':[688,600,705,806,759],
     'W':[81,94,93,69,61],
     'G':[162,162,162,162,162],
     'Playoffs':[0,1,1,0,0]
     
 }

# How to used __iterrows()__ method to iterate through the rows of our DataFrame

In [204]:
import pandas as pd

In [205]:
my_data = pd.DataFrame(data)

In [206]:
my_data

Team League  Year   RS   RA   W    G  Playoffs
0  ARI     NL  2012  734  688  81  162         0
1  ALT     NL  2012  700  600  94  162         1
2  BAL     AL  2012  712  705  93  162         1
3  BOS     AL  2012  734  806  69  162         0
4  CHC     NL  2012  613  759  61  162         0

# How to do any calculation and add a new __column__ to the above __DataFrame__

In [207]:
def calc_win_perc(wins,games_played):
    win_perc = wins / games_played
    return np.round(win_perc,2)

In [208]:
win_perc_list =[]

In [209]:
for i, row in my_data.iterrows():
    wins = row['W']
    games_played = row['G']
    win_perc1 = calc_win_perc(wins, games_played)
    win_perc_list.append(win_perc1)

In [210]:
my_data['WP'] = win_perc_list

In [211]:
my_data

Team League  Year   RS   RA   W    G  Playoffs    WP
0  ARI     NL  2012  734  688  81  162         0  0.50
1  ALT     NL  2012  700  600  94  162         1  0.58
2  BAL     AL  2012  712  705  93  162         1  0.57
3  BOS     AL  2012  734  806  69  162         0  0.43
4  CHC     NL  2012  613  759  61  162         0  0.38

In [213]:
add = my_data.iterrows()

In [222]:
## list(add)

In [223]:
for row_tuple in my_data.iterrows():
    print(row_tuple[1]['Team'])

ARI
ALT
BAL
BOS
CHC


# How to used __itertuples()__ method to iterate through the rows of our DataFrame

In [217]:
for row_nametuple in my_data.itertuples():
    print(row_nametuple)

Pandas(Index=0, Team='ARI', League='NL', Year=2012, RS=734, RA=688, W=81, G=162, Playoffs=0, WP=0.5)
Pandas(Index=1, Team='ALT', League='NL', Year=2012, RS=700, RA=600, W=94, G=162, Playoffs=1, WP=0.58)
Pandas(Index=2, Team='BAL', League='AL', Year=2012, RS=712, RA=705, W=93, G=162, Playoffs=1, WP=0.57)
Pandas(Index=3, Team='BOS', League='AL', Year=2012, RS=734, RA=806, W=69, G=162, Playoffs=0, WP=0.43)
Pandas(Index=4, Team='CHC', League='NL', Year=2012, RS=613, RA=759, W=61, G=162, Playoffs=0, WP=0.38)


In [221]:
print(row_nametuple.Team)

CHC


In [224]:
for row_tuple in my_data.itertuples():
    print(row_tuple.Team)

ARI
ALT
BAL
BOS
CHC


## Another example

In [225]:
my_data

Team League  Year   RS   RA   W    G  Playoffs    WP
0  ARI     NL  2012  734  688  81  162         0  0.50
1  ALT     NL  2012  700  600  94  162         1  0.58
2  BAL     AL  2012  712  705  93  162         1  0.57
3  BOS     AL  2012  734  806  69  162         0  0.43
4  CHC     NL  2012  613  759  61  162         0  0.38

In [226]:
def calc_run_diff(runs_scored, runs_allowed):
    run_diff = runs_scored - runs_allowed
    return run_diff

In [227]:
run_diffs_interrows =[]

In [228]:
for i, row in my_data.iterrows():
    run_dif = calc_run_diff(row['RS'],row['RA'])
    run_diffs_interrows.append(run_dif)
    

In [229]:
my_data['RD'] = run_diffs_interrows

In [230]:
my_data

Team League  Year   RS   RA   W    G  Playoffs    WP   RD
0  ARI     NL  2012  734  688  81  162         0  0.50   46
1  ALT     NL  2012  700  600  94  162         1  0.58  100
2  BAL     AL  2012  712  705  93  162         1  0.57    7
3  BOS     AL  2012  734  806  69  162         0  0.43  -72
4  CHC     NL  2012  613  759  61  162         0  0.38 -146

# The best alternative for the above loops is using __pandas.apply()__ method

In [231]:
## by using above same function

run_diffs_apply_objects = my_data.apply(
lambda row: calc_run_diff(row['RS'],row['RA']),
    axis =1 
)
# axis = 1 / mean loop or iterate  over rows

# axis = 0 / mean loop or iterate over columns

In [233]:
my_data['RD'] = run_diffs_apply_objects

In [234]:
my_data

Team League  Year   RS   RA   W    G  Playoffs    WP   RD
0  ARI     NL  2012  734  688  81  162         0  0.50   46
1  ALT     NL  2012  700  600  94  162         1  0.58  100
2  BAL     AL  2012  712  705  93  162         1  0.57    7
3  BOS     AL  2012  734  806  69  162         0  0.43  -72
4  CHC     NL  2012  613  759  61  162         0  0.38 -146